
services:

  db:
    container_name: songoclock_db
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: songoclock
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/dades.sql:/docker-entrypoint-initdb.d/dades.sql


  phpmyadmin:
    container_name: songoclock_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 9090:80
    depends_on:
      - db

  # node:
  #   container_name: songoclock_node
  #   image: node:20.11.1-bullseye-slim
  #   volumes:
  #     - ./node:/usr/src/app
  #   working_dir: /usr/src/app
  #   ports:
  #     - 8080:8080
  #   command: sh -c "npm install && npm run dev"
  #   depends_on:
  #     - db

  laravel:
    container_name: songoclock_laravel
    build: ./laravel
    volumes:
      - ./laravel:/var/www/html
    ports:
      - 8000:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: /bin/sh -c "chown -R www-data:www-data * && php artisan migrate --force && apache2-foreground "
    restart: always
    depends_on:
      - db
  
  nuxt:
    container_name: songoclock_nuxt
    image: node:20.11.1-bullseye-slim
    working_dir: /usr/src/app
    volumes:
      - ./nuxt:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
