services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin # Cambiado a la imagen estándar
    restart: always
    environment:
      PMA_ABSOLUTE_URI: https://timbre.inspedralbes.cat/pma/
    ports:
      - 9090:80
    depends_on:
      - db

  db:
    container_name: soundoclock_db
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rJNQQvVLV3MQphASEsWXw5Bw
      MYSQL_DATABASE: soundoclock
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/dades.sql:/docker-entrypoint-initdb.d/dades.sql

  node:
    container_name: soundoclock_node
    image: node:20.11.1-bullseye-slim
    restart: always
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run start"
    depends_on:
      - db

  laravel:
    container_name: soundoclock_laravel
    build: ./laravel
    ports:
      - 8000:80
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: /bin/sh -c "composer install && php artisan key:generate && chown -R www-data:www-data * && php artisan migrate --force && php artisan migrate && apache2-foreground"
    depends_on:
      - db

  nuxt:
    container_name: soundoclock_nuxt
    image: node:20.11.1-bullseye-slim
    working_dir: /usr/src/app
    volumes:
      - ./nuxt:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    tmpfs:
      - /tmp
    command: sh -c "node ./server/index.mjs -- --host=http://timbre.inspedralbes.cat:8080"

  mongodb:
    container_name: soundoclock_mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: WQezGsKWN8qbixs647ofrM
    volumes:
      - ./mongodb_data:/data/db

  mongo-express:
    container_name: soundoclock_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: WQezGsKWN8qbixs647ofrM
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: ypu8VW8jDdc3q2vShFPVuwTV
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring

networks:
  monitoring:
    external: true
