INSERT INTO songs (title, artist, genre, year, votes, created_at, updated_at) VALUES
('7 Rings', 'Ariana Grande', 'Pop', 2019, 0, NOW(), NOW()),
('Agua', 'Tainy, J Balvin', 'Reggaeton', 2020, 0, NOW(), NOW()),
('Baila Baila Baila', 'Ozuna', 'Reggaeton', 2019, 0, NOW(), NOW()),
('Bésame', 'Danna Paola, Lola Indigo', 'Pop', 2021, 0, NOW(), NOW()),
('Bichota', 'Karol G', 'Reggaeton', 2020, 0, NOW(), NOW()),
('Billie Jean', 'Michael Jackson', 'Pop', 1982, 0, NOW(), NOW()),
('Bitter Sweet Symphony', 'The Verve', 'Rock', 1997, 0, NOW(), NOW()),
('Bohemian Rhapsody', 'Queen', 'Rock', 1975, 0, NOW(), NOW()),
('Boys Don’t Cry', 'The Cure', 'New Wave', 1979, 0, NOW(), NOW()),
('Cheap Thrills', 'Sia ft. Sean Paul', 'Pop', 2016, 0, NOW(), NOW()),
('Closer', 'The Chainsmokers ft. Halsey', 'EDM', 2016, 0, NOW(), NOW()),
('Dime Cómo Quieres', 'Christian Nodal, Ángela Aguilar', 'Ranchera', 2020, 0, NOW(), NOW()),
('Dákiti', 'Bad Bunny, Jhay Cortez', 'Reggaeton', 2020, 0, NOW(), NOW()),
('De Una Vez', 'Selena Gomez', 'Pop', 2021, 0, NOW(), NOW()),
('Despacito', 'Luis Fonsi ft. Daddy Yankee', 'Reggaeton', 2017, 0, NOW(), NOW()),
('Favorito', 'Camilo', 'Pop', 2020, 0, NOW(), NOW()),
('Happier', 'Marshmello ft. Bastille', 'Pop', 2018, 0, NOW(), NOW()),
('Havana', 'Camila Cabello ft. Young Thug', 'Pop', 2017, 0, NOW(), NOW()),
('Hawái', 'Maluma', 'Reggaeton', 2020, 0, NOW(), NOW()),
('Hallelujah', 'Leonard Cohen', 'Folk', 1984, 0, NOW(), NOW()),
('Hello', 'Adele', 'Pop', 2015, 0, NOW(), NOW()),
('Hey Jude', 'The Beatles', 'Rock', 1968, 0, NOW(), NOW()),
('Hey Ya!', 'OutKast', 'Hip Hop', 2003, 0, NOW(), NOW()),
('Hotel California', 'Eagles', 'Rock', 1976, 0, NOW(), NOW()),
('Humble', 'Kendrick Lamar', 'Hip Hop', 2017, 0, NOW(), NOW()),
('Hurt', 'Johnny Cash', 'Country', 2002, 0, NOW(), NOW()),
('La Cama', 'Lunay', 'Reggaeton', 2020, 0, NOW(), NOW()),
('La Noche de Anoche', 'Bad Bunny, Rosalía', 'Reggaeton', 2020, 0, NOW(), NOW()),
('La Tóxica', 'Farruko', 'Reggaeton', 2020, 0, NOW(), NOW()),
('Like a Rolling Stone', 'Bob Dylan', 'Rock', 1965, 0, NOW(), NOW()),
('Losing My Religion', 'R.E.M.', 'Alternative Rock', 1991, 0, NOW(), NOW()),
('Love Yourself', 'Justin Bieber', 'Pop', 2015, 0, NOW(), NOW()),
('Miedo', 'Amaia Romero', 'Pop', 2021, 0, NOW(), NOW()),
('Nothing Else Matters', 'Metallica', 'Heavy Metal', 1992, 0, NOW(), NOW()),
('One', 'Metallica', 'Heavy Metal', 1988, 0, NOW(), NOW()),
('Purple Haze', 'Jimi Hendrix', 'Rock', 1967, 0, NOW(), NOW()),
('Qué Más Pues?', 'J Balvin, Maria Becerra', 'Reggaeton', 2021, 0, NOW(), NOW()),
('Relación (Remix)', 'Sech, Daddy Yankee, J Balvin, Rosalía, Farruko', 'Reggaeton', 2020, 0, NOW(), NOW()),
('Rojo', 'J Balvin', 'Pop', 2020, 0, NOW(), NOW()),
('Roses', 'The Chainsmokers ft. Rozes', 'EDM', 2015, 0, NOW(), NOW()),
('Senorita', 'Shawn Mendes, Camila Cabello', 'Pop', 2019, 0, NOW(), NOW()),
('Shape of You', 'Ed Sheeran', 'Pop', 2017, 0, NOW(), NOW()),
('Shake It Off', 'Taylor Swift', 'Pop', 2014, 0, NOW(), NOW()),
('Smells Like Teen Spirit', 'Nirvana', 'Grunge', 1991, 0, NOW(), NOW()),
('Sorry', 'Justin Bieber', 'Pop', 2015, 0, NOW(), NOW()),
('Stairway to Heaven', 'Led Zeppelin', 'Rock', 1971, 0, NOW(), NOW()),
('Stitches', 'Shawn Mendes', 'Pop', 2015, 0, NOW(), NOW()),
('Sucker', 'Jonas Brothers', 'Pop', 2019, 0, NOW(), NOW()),
('Shape of You', 'Ed Sheeran', 'Pop', 2017, 0, NOW(), NOW()),
('Tusa', 'Karol G, Nicki Minaj', 'Reggaeton', 2019, 0, NOW(), NOW()),
('Thriller', 'Michael Jackson', 'Pop', 1982, 0, NOW(), NOW()),
('Thunder', 'Imagine Dragons', 'Pop Rock', 2017, 0, NOW(), NOW()),
('Uptown Funk', 'Mark Ronson ft. Bruno Mars', 'Funk', 2014, 0, NOW(), NOW()),
('Un Día (One Day)', 'J Balvin, Dua Lipa, Bad Bunny, Tainy', 'Reggaeton', 2020, 0, NOW(), NOW()),
('Vida de Rico', 'Camilo', 'Pop', 2020, 0, NOW(), NOW());
